/**
 * Financial Policy Language (FPL) — Recursive Descent Parser
 *
 * Transforms the Lexer `Token[]` stream into a strongly-typed Abstract Syntax Tree
 * (`ASTProgram`) with full source locations, parent-child links, and panic-mode
 * error recovery.
 *
 * Strictly adheres to phase boundaries:
 * - Reads ONLY the Lexer token stream (never reads raw source text)
 * - Does NOT perform semantic analysis, symbol table resolution, IR generation,
 *   optimization, or runtime execution.
 */
import type { Token } from '../lexer/lexer.interface';
import { TokenType } from '../lexer/token-types';
import { ASTRepository } from '../ast/ast-repository';
import type { ASTProgram, ASTImportDeclaration, ASTConstantDeclaration, ASTVariableDeclaration, ASTFunctionDeclaration, ASTPolicyDeclaration, ASTRuleDeclaration, ASTTypeAnnotation, ASTStatementNode, ASTIfStatement, ASTSetStatement, ASTEmitStatement, ASTApplyStatement, ASTMatchStatement, ASTForStatement, ASTWhileStatement, ASTForeachStatement, ASTTryStatement, ASTReturnStatement, ASTCallStatement, ASTLogStatement, ASTAssertStatement, ASTThrowStatement, ASTDecisionStatement, ASTExpressionNode } from '../ast/ast.interface';
import { type SyntaxDiagnostic } from './syntax-diagnostics';
import type { IParser, ParseResult, ParseError } from './parser.interface';
export declare class Parser implements IParser {
    private stream;
    private context;
    private diagnostics;
    private recovery;
    private builder;
    private printer;
    private repository;
    /**
     * Creates a new Recursive Descent Parser instance.
     *
     * @param tokens     - Optional initial token stream generated by the Lexer
     * @param repository - Optional shared `ASTRepository` instance
     */
    constructor(tokens?: Token[], repository?: ASTRepository);
    /**
     * Returns the central `ASTRepository` ("Source of Truth").
     */
    getRepository(): ASTRepository;
    peek(lookahead?: number): Token;
    match(...types: TokenType[]): boolean;
    consume(): Token;
    expect(type: TokenType, code: string, message: string, suggestedFix: string): Token;
    synchronize(): void;
    recover(_error?: ParseError): void;
    hasErrors(): boolean;
    getDiagnostics(): SyntaxDiagnostic[];
    /**
     * Parses the token stream, saves the resulting `ASTProgram` into the central
     * `ASTRepository` ("Source of Truth"), and produces a complete {@link ParseResult}.
     */
    parse(tokens?: Token[]): ParseResult;
    /**
     * Grammar Rule:
     * `program ::= { import_decl | const_decl | var_decl | function_decl | policy_decl | rule_decl | statement }`
     */
    parseProgram(): ASTProgram;
    /**
     * Grammar Rule:
     * `import_decl ::= "IMPORT" STRING [ "AS" IDENTIFIER ]`
     */
    parseImportDeclaration(): ASTImportDeclaration;
    /**
     * Grammar Rule:
     * `const_decl ::= "CONST" IDENTIFIER [ ":" type_spec ] "=" expr`
     */
    parseConstantDeclaration(): ASTConstantDeclaration;
    /**
     * Grammar Rule:
     * `var_decl ::= ("LET" | "VAR") IDENTIFIER [ ":" type_spec ] [ "=" expr ]`
     */
    parseVariableDeclaration(): ASTVariableDeclaration;
    /**
     * Grammar Rule:
     * `type_spec ::= "array" "OF" type_spec | primitive_or_domain_type [ "[" "]" ]`
     */
    parseTypeAnnotation(): ASTTypeAnnotation;
    private consumeTypeToken;
    /**
     * Grammar Rule:
     * `function_decl ::= "FUNCTION" IDENTIFIER "(" [ param_list ] ")" [ ":" type_spec ] { statement } "END"`
     */
    parseFunction(): ASTFunctionDeclaration;
    /**
     * Grammar Rule:
     * ```ebnf
     * policy_decl ::= "POLICY" IDENTIFIER
     *                 [ input_block ]
     *                 [ output_block ]
     *                 [ when_block ]
     *                 [ then_block ]
     *                 [ else_block ]
     *                 { rule_decl }
     *                 "END"
     * ```
     */
    parsePolicy(): ASTPolicyDeclaration;
    private parseInputBlock;
    private parseOutputBlock;
    private parseParameterBlockEntries;
    private parseWhenBlock;
    private parseThenBlock;
    private parseElseBlock;
    /**
     * Grammar Rule:
     * `rule_decl ::= "RULE" IDENTIFIER [ "WHEN" expr [ "THEN" ] ] { statement } "END"`
     */
    parseRuleDeclaration(): ASTRuleDeclaration;
    /**
     * Dispatches to the appropriate statement parsing function based on the
     * current lookahead token.
     */
    parseStatement(): ASTStatementNode | null;
    /**
     * Grammar Rule:
     * `set_stmt ::= "SET" lvalue ("=" | "+=" | "-=" | "*=" | "/=") expr`
     */
    parseSetStatement(): ASTSetStatement;
    /**
     * Grammar Rule:
     * `emit_stmt ::= "EMIT" IDENTIFIER "=" expr`
     */
    parseEmitStatement(): ASTEmitStatement;
    /**
     * Grammar Rule:
     * `apply_stmt ::= "APPLY" IDENTIFIER`
     */
    parseApplyStatement(): ASTApplyStatement;
    /**
     * Grammar Rule:
     * ```ebnf
     * if_stmt ::= "IF" expr "THEN" { statement }
     *             { "ELSEIF" expr "THEN" { statement } }
     *             [ "ELSE" { statement } ]
     *             "END"
     * ```
     */
    parseIfStatement(): ASTIfStatement;
    /**
     * Grammar Rule:
     * `match_stmt ::= "MATCH" expr { "CASE" expr { "," expr } "THEN" { statement } } [ "DEFAULT" "THEN" { statement } ] "END"`
     */
    parseMatchStatement(): ASTMatchStatement;
    /**
     * Grammar Rule:
     * `for_stmt ::= "FOR" IDENTIFIER ("FROM" | "IN" | "=") expr ("TO" | "..") expr [ "STEP" expr ] [ "DO" ] { statement } "END"`
     */
    parseForStatement(): ASTForStatement;
    /**
     * Grammar Rule:
     * `while_stmt ::= "WHILE" expr [ "DO" ] { statement } "END"`
     */
    parseWhileStatement(): ASTWhileStatement;
    /**
     * Grammar Rule:
     * `foreach_stmt ::= "FOREACH" IDENTIFIER "IN" expr [ "DO" ] { statement } "END"`
     */
    parseForeachStatement(): ASTForeachStatement;
    /**
     * Grammar Rule:
     * `try_stmt ::= "TRY" { statement } "CATCH" [ IDENTIFIER ] { statement } "END"`
     */
    parseTryStatement(): ASTTryStatement;
    /**
     * Grammar Rule:
     * `return_stmt ::= "RETURN" [ expr ]`
     */
    parseReturnStatement(): ASTReturnStatement;
    /**
     * Grammar Rule:
     * `call_stmt ::= "CALL" qualified_name [ "(" arg_list ")" | "WITH" named_arg_list ] [ "RETURNS" IDENTIFIER ]`
     */
    parseCallStatement(): ASTCallStatement;
    /**
     * Grammar Rule:
     * `log_stmt ::= ("LOG" | "WARN") expr`
     */
    parseLogStatement(): ASTLogStatement;
    /**
     * Grammar Rule:
     * `assert_stmt ::= "ASSERT" expr [ "," expr ]`
     */
    parseAssertStatement(): ASTAssertStatement;
    /**
     * Grammar Rule:
     * `throw_stmt ::= "THROW" [ "ERROR" ] [ "(" ] expr [ "," expr ] [ ")" ]`
     */
    parseThrowStatement(): ASTThrowStatement;
    /**
     * Grammar Rule:
     * `decision_stmt ::= ("ALLOW" | "DENY" | "REVIEW") [ "WITH" [ "reason" "=" ] expr [ "AND" "assignTo" "=" expr ] ]`
     */
    parseDecisionStatement(): ASTDecisionStatement;
    /**
     * Parses direct assignment (`x = expr`, `x += expr`) or an expression statement.
     */
    private parseAssignmentOrExpressionStatement;
    private consumeAssignmentOperator;
    /**
     * Entry point for expression parsing (lowest precedence to highest):
     * 1. Null-Coalescing (`??`)
     * 2. Logical OR (`OR`)
     * 3. Logical AND (`AND`)
     * 4. Logical NOT (`NOT`)
     * 5. Comparison (`==`, `=`, `!=`, `<`, `>`, `<=`, `>=`)
     * 6. Membership & Null Checks (`IN`, `NOT IN`, `BETWEEN...AND`, `CONTAINS`, `IS NULL`, `IS NOT NULL`)
     * 7. Range (`..`, `TO`)
     * 8. Additive (`+`, `-`)
     * 9. Multiplicative (`*`, `/`, `%`)
     * 10. Percentage Application (`OF`)
     * 11. Exponentiation (`^`)
     * 12. Unary (`-`, `+`, `NOT`)
     * 13. Postfix & Primary (Literals, Identifiers, Function Calls, Policy Calls, Member `.`, Index `[]`, `(...)`, Ternary `IF...THEN...ELSE`)
     */
    parseExpression(): ASTExpressionNode;
    private parseNullCoalesceExpression;
    private parseLogicalOrExpression;
    private parseLogicalAndExpression;
    private parseLogicalNotExpression;
    private parseComparisonExpression;
    /**
     * In FPL (`=`) can be used as an equality comparison inside `WHEN` / `IF` conditions,
     * while `SET x = y` or top-level `x = y` is an assignment statement.
     */
    private isEqualityComparisonAssign;
    private parseMembershipExpression;
    private parseRangeExpression;
    private parseAdditiveExpression;
    private parseMultiplicativeExpression;
    private parsePercentageOfExpression;
    private parsePowerExpression;
    private parseUnaryExpression;
    private parsePrimaryOrPostfix;
    private parsePrimaryExpression;
    private parseArgumentExpressionList;
    private parseQualifiedName;
    private expectIdentifierLike;
    private isTopLevelDeclarationStart;
    private isTopLevelStarterExceptRule;
}
/**
 * Convenience API that parses a `Token[]` stream directly into a {@link ParseResult}.
 */
export declare function parseTokens(tokens: Token[]): ParseResult;
//# sourceMappingURL=parser.d.ts.map