"use strict";
/**
 * Financial Policy Language (FPL) — Recursive Descent Parser
 *
 * Transforms the Lexer `Token[]` stream into a strongly-typed Abstract Syntax Tree
 * (`ASTProgram`) with full source locations, parent-child links, and panic-mode
 * error recovery.
 *
 * Strictly adheres to phase boundaries:
 * - Reads ONLY the Lexer token stream (never reads raw source text)
 * - Does NOT perform semantic analysis, symbol table resolution, IR generation,
 *   optimization, or runtime execution.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Parser = void 0;
exports.parseTokens = parseTokens;
const token_types_1 = require("../lexer/token-types");
const ast_builder_1 = require("../ast/ast-builder");
const ast_pretty_printer_1 = require("../ast/ast-pretty-printer");
const ast_repository_1 = require("../ast/ast-repository");
const token_stream_1 = require("./token-stream");
const parser_context_1 = require("./parser-context");
const syntax_diagnostics_1 = require("./syntax-diagnostics");
const recovery_engine_1 = require("./recovery-engine");
const BUILTIN_TYPE_TOKEN_SET = new Set(Object.values(token_types_1.TYPE_KEYWORDS));
class Parser {
    stream;
    context;
    diagnostics;
    recovery;
    builder;
    printer;
    repository;
    /**
     * Creates a new Recursive Descent Parser instance.
     *
     * @param tokens     - Optional initial token stream generated by the Lexer
     * @param repository - Optional shared `ASTRepository` instance
     */
    constructor(tokens = [], repository) {
        const fileName = tokens[0]?.fileName ?? 'workspace.fpl';
        this.stream = new token_stream_1.TokenStream(tokens);
        this.context = new parser_context_1.ParserContext();
        this.diagnostics = new syntax_diagnostics_1.SyntaxDiagnostics(this.stream);
        this.recovery = new recovery_engine_1.RecoveryEngine(this.stream, this.context);
        this.builder = new ast_builder_1.ASTBuilder(fileName);
        this.printer = new ast_pretty_printer_1.ASTPrettyPrinter();
        this.repository = repository ?? new ast_repository_1.ASTRepository();
    }
    /**
     * Returns the central `ASTRepository` ("Source of Truth").
     */
    getRepository() {
        return this.repository;
    }
    // ─── Core Stream & Recovery Primitives ────────────────────────────────────
    peek(lookahead = 0) {
        return this.stream.peek(lookahead);
    }
    match(...types) {
        return this.stream.match(...types);
    }
    consume() {
        return this.stream.consume();
    }
    expect(type, code, message, suggestedFix) {
        if (this.stream.check(type)) {
            return this.stream.consume();
        }
        const offending = this.stream.peek();
        this.diagnostics.report({
            code,
            message,
            token: offending,
            expectedToken: type,
            suggestedFix,
        });
        this.context.setPanicMode(true);
        // Return a synthetic token at the current position so AST construction can proceed
        return {
            ...offending,
            type,
            lexeme: offending.lexeme,
        };
    }
    synchronize() {
        this.recovery.synchronize();
    }
    recover(_error) {
        this.synchronize();
    }
    hasErrors() {
        return this.diagnostics.hasErrors();
    }
    getDiagnostics() {
        return this.diagnostics.getDiagnostics();
    }
    // ─── Top-Level Entry Point ────────────────────────────────────────────────
    /**
     * Parses the token stream, saves the resulting `ASTProgram` into the central
     * `ASTRepository` ("Source of Truth"), and produces a complete {@link ParseResult}.
     */
    parse(tokens) {
        const fileName = tokens?.[0]?.fileName ?? this.stream.peek().fileName ?? 'workspace.fpl';
        if (tokens !== undefined) {
            this.stream = new token_stream_1.TokenStream(tokens);
            this.context = new parser_context_1.ParserContext();
            this.diagnostics = new syntax_diagnostics_1.SyntaxDiagnostics(this.stream);
            this.recovery = new recovery_engine_1.RecoveryEngine(this.stream, this.context);
            this.builder = new ast_builder_1.ASTBuilder(fileName);
        }
        else {
            this.stream.reset();
            this.context.reset();
            this.diagnostics.clear();
            this.builder.reset();
        }
        const ast = this.parseProgram();
        this.repository.commit(ast, fileName);
        const diags = this.diagnostics.getDiagnostics();
        return {
            ast,
            repository: this.repository,
            diagnostics: diags,
            errors: diags,
            hasErrors: this.diagnostics.hasErrors(),
            prettyTree: this.repository.toPrettyTree(),
            formattedDiagnostics: this.diagnostics.formatDiagnostics(),
            json: this.repository.toJSON(),
            graph: this.repository.toGraph(),
            graphvizDot: this.repository.toGraphvizDot(),
        };
    }
    /**
     * Grammar Rule:
     * `program ::= { import_decl | const_decl | var_decl | function_decl | policy_decl | rule_decl | statement }`
     */
    parseProgram() {
        const startToken = this.peek();
        const imports = [];
        const constants = [];
        const variables = [];
        const functions = [];
        const policies = [];
        const rules = [];
        const statements = [];
        let seenNonImport = false;
        while (!this.stream.isAtEnd()) {
            const current = this.peek();
            // Skip stray semicolons
            if (this.match(token_types_1.TokenType.SEMICOLON)) {
                continue;
            }
            if (this.stream.check(token_types_1.TokenType.IMPORT)) {
                if (seenNonImport) {
                    this.diagnostics.report({
                        code: 'FPL-S004',
                        message: 'IMPORT declarations must appear at the top of the file before other declarations',
                        token: current,
                        expectedToken: 'Top-of-file IMPORT',
                        suggestedFix: 'Move this IMPORT statement to the top of the .fpl file.',
                    });
                }
                imports.push(this.parseImportDeclaration());
                continue;
            }
            seenNonImport = true;
            if (this.stream.check(token_types_1.TokenType.CONST)) {
                constants.push(this.parseConstantDeclaration());
                continue;
            }
            if (this.stream.check(token_types_1.TokenType.LET) || this.stream.check(token_types_1.TokenType.VAR)) {
                variables.push(this.parseVariableDeclaration());
                continue;
            }
            if (this.stream.check(token_types_1.TokenType.FUNCTION)) {
                functions.push(this.parseFunction());
                continue;
            }
            if (this.stream.check(token_types_1.TokenType.POLICY)) {
                policies.push(this.parsePolicy());
                continue;
            }
            if (this.stream.check(token_types_1.TokenType.RULE)) {
                rules.push(this.parseRuleDeclaration());
                continue;
            }
            // Unexpected closing keyword at top level
            if (this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.ELSE, token_types_1.TokenType.ELSEIF, token_types_1.TokenType.THEN, token_types_1.TokenType.RPAREN, token_types_1.TokenType.RBRACE, token_types_1.TokenType.RBRACKET)) {
                const unexpected = this.consume();
                this.diagnostics.report({
                    code: 'FPL-S002',
                    message: `Unexpected '${unexpected.lexeme}' at top level without a matching opening block`,
                    token: unexpected,
                    expectedToken: 'POLICY, FUNCTION, CONST, LET, or RULE declaration',
                    suggestedFix: `Remove the stray '${unexpected.lexeme}' or add the missing opening block keyword.`,
                });
                continue;
            }
            // Fallback: parse top-level statement or recover
            const stmt = this.parseStatement();
            if (stmt) {
                statements.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        const endToken = this.stream.previous();
        return this.builder.buildProgram({
            imports,
            constants,
            variables,
            functions,
            policies,
            rules,
            statements,
        }, startToken, endToken);
    }
    // ─── Top-Level Declaration Parsers ────────────────────────────────────────
    /**
     * Grammar Rule:
     * `import_decl ::= "IMPORT" STRING [ "AS" IDENTIFIER ]`
     */
    parseImportDeclaration() {
        const startToken = this.expect(token_types_1.TokenType.IMPORT, 'FPL-S002', "Expected 'IMPORT' keyword", "Start the import declaration with 'IMPORT'.");
        const pathToken = this.expect(token_types_1.TokenType.STRING, 'FPL-S002', 'Expected string literal path after IMPORT', 'Provide a quoted file path, e.g. `IMPORT "shared/common.fpl"`.');
        const cleanPath = typeof pathToken.literal === 'string'
            ? pathToken.literal
            : pathToken.lexeme.replace(/^["']|["']$/g, '');
        let alias = null;
        let endToken = pathToken;
        if (this.match(token_types_1.TokenType.AS)) {
            const aliasToken = this.expect(token_types_1.TokenType.IDENTIFIER, 'FPL-S002', "Expected alias identifier after 'AS'", 'Provide a PascalCase alias name, e.g. `AS CreditLib`.');
            alias = aliasToken.lexeme;
            endToken = aliasToken;
        }
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildImport(cleanPath, alias, startToken, endToken);
    }
    /**
     * Grammar Rule:
     * `const_decl ::= "CONST" IDENTIFIER [ ":" type_spec ] "=" expr`
     */
    parseConstantDeclaration() {
        const startToken = this.expect(token_types_1.TokenType.CONST, 'FPL-S002', "Expected 'CONST' keyword", "Begin constant declaration with 'CONST'.");
        const nameToken = this.expectIdentifierLike('Expected constant name after CONST', 'Provide an UPPER_SNAKE_CASE identifier, e.g. `CONST MAX_LOAN : currency = ...`.');
        let typeAnnotation = null;
        if (this.match(token_types_1.TokenType.COLON)) {
            typeAnnotation = this.parseTypeAnnotation();
        }
        this.expect(token_types_1.TokenType.ASSIGN, 'FPL-S002', `Expected '=' in constant declaration '${nameToken.lexeme}'`, `Assign an initial value to '${nameToken.lexeme}', e.g. '= 100'.`);
        const valueExpr = this.parseExpression();
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildConstantDeclaration(nameToken.lexeme, typeAnnotation, valueExpr, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `var_decl ::= ("LET" | "VAR") IDENTIFIER [ ":" type_spec ] [ "=" expr ]`
     */
    parseVariableDeclaration() {
        const startToken = this.consume(); // LET or VAR
        const kind = startToken.type === token_types_1.TokenType.VAR ? 'VAR' : 'LET';
        const nameToken = this.expectIdentifierLike(`Expected variable name after '${kind}'`, `Provide a valid camelCase variable name after '${kind}'.`);
        let typeAnnotation = null;
        if (this.match(token_types_1.TokenType.COLON)) {
            typeAnnotation = this.parseTypeAnnotation();
        }
        let initializer = null;
        if (this.match(token_types_1.TokenType.ASSIGN)) {
            initializer = this.parseExpression();
        }
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildVariableDeclaration(kind, nameToken.lexeme, typeAnnotation, initializer, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `type_spec ::= "array" "OF" type_spec | primitive_or_domain_type [ "[" "]" ]`
     */
    parseTypeAnnotation() {
        const startToken = this.peek();
        if (this.match(token_types_1.TokenType.ARRAY_TYPE)) {
            this.match(token_types_1.TokenType.OF);
            const elementTypeToken = this.consumeTypeToken();
            return this.builder.buildTypeAnnotation(`array OF ${elementTypeToken.lexeme}`, true, elementTypeToken.lexeme, startToken, elementTypeToken);
        }
        const baseToken = this.consumeTypeToken();
        let isArray = false;
        let endToken = baseToken;
        if (this.match(token_types_1.TokenType.LBRACKET)) {
            endToken = this.expect(token_types_1.TokenType.RBRACKET, 'FPL-S002', "Expected closing ']' in array type annotation", "Add ']' to complete the array type.");
            isArray = true;
        }
        return this.builder.buildTypeAnnotation(baseToken.lexeme, isArray, isArray ? baseToken.lexeme : null, startToken, endToken);
    }
    consumeTypeToken() {
        const tok = this.peek();
        if (BUILTIN_TYPE_TOKEN_SET.has(tok.type) || tok.type === token_types_1.TokenType.IDENTIFIER) {
            return this.consume();
        }
        this.diagnostics.report({
            code: 'FPL-S002',
            message: `Expected type name but found '${tok.lexeme}'`,
            token: tok,
            expectedToken: 'int, decimal, currency, percentage, string, boolean, date, customer, loan, or account',
            suggestedFix: 'Specify a valid FPL data type after `:`.',
        });
        return {
            ...tok,
            type: token_types_1.TokenType.IDENTIFIER,
            lexeme: 'unknown_type',
        };
    }
    /**
     * Grammar Rule:
     * `function_decl ::= "FUNCTION" IDENTIFIER "(" [ param_list ] ")" [ ":" type_spec ] { statement } "END"`
     */
    parseFunction() {
        const startToken = this.expect(token_types_1.TokenType.FUNCTION, 'FPL-S002', "Expected 'FUNCTION' keyword", "Start function declaration with 'FUNCTION'.");
        this.context.enterBlock('FUNCTION');
        const nameToken = this.expectIdentifierLike('Expected function name after FUNCTION', 'Provide a camelCase function name, e.g. `FUNCTION calculateEMI(...)`.');
        this.expect(token_types_1.TokenType.LPAREN, 'FPL-S002', `Expected '(' after function name '${nameToken.lexeme}'`, `Add '(' to begin parameter list for '${nameToken.lexeme}'.`);
        const parameters = [];
        if (!this.stream.check(token_types_1.TokenType.RPAREN) && !this.stream.isAtEnd()) {
            do {
                if (this.stream.check(token_types_1.TokenType.RPAREN))
                    break;
                const paramStart = this.peek();
                const paramName = this.expectIdentifierLike('Expected parameter name', 'Provide a valid parameter identifier.');
                this.expect(token_types_1.TokenType.COLON, 'FPL-S002', `Expected ':' after parameter '${paramName.lexeme}'`, `Specify parameter type, e.g. '${paramName.lexeme}: decimal'.`);
                const paramType = this.parseTypeAnnotation();
                parameters.push(this.builder.buildParameter(paramName.lexeme, paramType, paramStart, this.stream.previous()));
            } while (this.match(token_types_1.TokenType.COMMA));
        }
        this.expect(token_types_1.TokenType.RPAREN, 'FPL-S002', `Expected ')' after parameters in function '${nameToken.lexeme}'`, "Add ')' to close the function parameter list.");
        let returnType = null;
        if (this.match(token_types_1.TokenType.COLON)) {
            returnType = this.parseTypeAnnotation();
        }
        const body = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.check(token_types_1.TokenType.END) &&
            !this.isTopLevelDeclarationStart()) {
            const stmt = this.parseStatement();
            if (stmt) {
                body.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', `Missing 'END' for FUNCTION '${nameToken.lexeme}'`, `Close FUNCTION '${nameToken.lexeme}' with 'END'.`);
        this.context.exitBlock();
        return this.builder.buildFunctionDeclaration(nameToken.lexeme, parameters, returnType, body, startToken, endToken);
    }
    /**
     * Grammar Rule:
     * ```ebnf
     * policy_decl ::= "POLICY" IDENTIFIER
     *                 [ input_block ]
     *                 [ output_block ]
     *                 [ when_block ]
     *                 [ then_block ]
     *                 [ else_block ]
     *                 { rule_decl }
     *                 "END"
     * ```
     */
    parsePolicy() {
        const startToken = this.expect(token_types_1.TokenType.POLICY, 'FPL-S002', "Expected 'POLICY' keyword", "Start policy declaration with 'POLICY'.");
        this.context.enterBlock('POLICY');
        const nameToken = this.expectIdentifierLike('Expected policy name after POLICY', 'Provide a PascalCase policy identifier, e.g. `POLICY LoanApproval`.');
        let inputBlock = null;
        let outputBlock = null;
        let whenBlock = null;
        let thenBlock = null;
        let elseBlock = null;
        const rules = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.check(token_types_1.TokenType.END) &&
            !this.isTopLevelStarterExceptRule()) {
            if (this.stream.check(token_types_1.TokenType.INPUT)) {
                inputBlock = this.parseInputBlock();
            }
            else if (this.stream.check(token_types_1.TokenType.OUTPUT)) {
                outputBlock = this.parseOutputBlock();
            }
            else if (this.stream.check(token_types_1.TokenType.WHEN)) {
                whenBlock = this.parseWhenBlock();
            }
            else if (this.stream.check(token_types_1.TokenType.THEN)) {
                thenBlock = this.parseThenBlock();
            }
            else if (this.stream.check(token_types_1.TokenType.ELSE)) {
                elseBlock = this.parseElseBlock();
            }
            else if (this.stream.check(token_types_1.TokenType.RULE)) {
                rules.push(this.parseRuleDeclaration());
            }
            else {
                // Handle statements placed directly in policy body or missing WHEN/THEN
                const offending = this.peek();
                if (!thenBlock) {
                    this.diagnostics.report({
                        code: 'FPL-S005',
                        message: `Expected policy section ('INPUT', 'OUTPUT', 'WHEN', 'THEN', or 'ELSE') inside POLICY '${nameToken.lexeme}', found '${offending.lexeme}'`,
                        token: offending,
                        expectedToken: 'INPUT, OUTPUT, WHEN, THEN, ELSE, or END',
                        suggestedFix: 'Place policy statements inside a `THEN` or `ELSE` block.',
                    });
                    const strayStmts = [];
                    const stmt = this.parseStatement();
                    if (stmt) {
                        strayStmts.push(stmt);
                        thenBlock = this.builder.buildThenBlock(strayStmts, offending, this.stream.previous());
                    }
                    else {
                        this.synchronize();
                    }
                }
                else {
                    const stmt = this.parseStatement();
                    if (stmt) {
                        thenBlock.statements.push(stmt);
                        thenBlock.children.push(stmt);
                        stmt.parent = thenBlock;
                    }
                    else {
                        this.synchronize();
                    }
                }
            }
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', `Missing 'END' to close POLICY '${nameToken.lexeme}'`, `Add 'END' at the end of POLICY '${nameToken.lexeme}'.`);
        this.context.exitBlock();
        return this.builder.buildPolicyDeclaration({
            name: nameToken.lexeme,
            inputBlock,
            outputBlock,
            whenBlock,
            thenBlock,
            elseBlock,
            rules,
        }, startToken, endToken);
    }
    parseInputBlock() {
        const startToken = this.consume(); // INPUT
        const parameters = this.parseParameterBlockEntries();
        return this.builder.buildInputBlock(parameters, startToken, this.stream.previous());
    }
    parseOutputBlock() {
        const startToken = this.consume(); // OUTPUT
        const parameters = this.parseParameterBlockEntries();
        return this.builder.buildOutputBlock(parameters, startToken, this.stream.previous());
    }
    parseParameterBlockEntries() {
        const parameters = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.INPUT, token_types_1.TokenType.OUTPUT, token_types_1.TokenType.WHEN, token_types_1.TokenType.THEN, token_types_1.TokenType.ELSE, token_types_1.TokenType.RULE, token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
            if (this.peek().type === token_types_1.TokenType.IDENTIFIER && this.peek(1).type === token_types_1.TokenType.COLON) {
                const paramStart = this.consume();
                this.consume(); // ':'
                const typeAnn = this.parseTypeAnnotation();
                this.match(token_types_1.TokenType.COMMA, token_types_1.TokenType.SEMICOLON);
                parameters.push(this.builder.buildParameter(paramStart.lexeme, typeAnn, paramStart, this.stream.previous()));
            }
            else {
                break;
            }
        }
        return parameters;
    }
    parseWhenBlock() {
        const startToken = this.consume(); // WHEN
        const condition = this.parseExpression();
        // Check if the user forgot `THEN` immediately after `WHEN <condition>`
        if (!this.stream.checkAny(token_types_1.TokenType.THEN, token_types_1.TokenType.ELSE, token_types_1.TokenType.END, token_types_1.TokenType.OUTPUT, token_types_1.TokenType.INPUT) &&
            !this.stream.isAtEnd()) {
            const nextTok = this.peek();
            this.diagnostics.report({
                code: 'FPL-S003',
                message: `Missing 'THEN' after WHEN condition before '${nextTok.lexeme}'`,
                token: nextTok,
                expectedToken: 'THEN',
                suggestedFix: "Add 'THEN' after the WHEN condition expression.",
            });
        }
        return this.builder.buildWhenBlock(condition, startToken, this.stream.previous());
    }
    parseThenBlock() {
        const startToken = this.consume(); // THEN
        const statements = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.ELSE, token_types_1.TokenType.END, token_types_1.TokenType.RULE, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
            const stmt = this.parseStatement();
            if (stmt) {
                statements.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        return this.builder.buildThenBlock(statements, startToken, this.stream.previous());
    }
    parseElseBlock() {
        const startToken = this.consume(); // ELSE
        const statements = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.RULE, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
            const stmt = this.parseStatement();
            if (stmt) {
                statements.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        return this.builder.buildElseBlock(statements, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `rule_decl ::= "RULE" IDENTIFIER [ "WHEN" expr [ "THEN" ] ] { statement } "END"`
     */
    parseRuleDeclaration() {
        const startToken = this.expect(token_types_1.TokenType.RULE, 'FPL-S002', "Expected 'RULE' keyword", "Start rule declaration with 'RULE'.");
        this.context.enterBlock('RULE');
        const nameToken = this.expectIdentifierLike('Expected rule name after RULE', 'Provide a PascalCase rule name, e.g. `RULE CreditScoreCheck`.');
        let condition = null;
        if (this.match(token_types_1.TokenType.WHEN)) {
            condition = this.parseExpression();
            this.match(token_types_1.TokenType.THEN);
        }
        const statements = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.check(token_types_1.TokenType.END) &&
            !this.isTopLevelDeclarationStart()) {
            const stmt = this.parseStatement();
            if (stmt) {
                statements.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', `Missing 'END' for RULE '${nameToken.lexeme}'`, `Close RULE '${nameToken.lexeme}' with 'END'.`);
        this.context.exitBlock();
        return this.builder.buildRuleDeclaration(nameToken.lexeme, condition, statements, startToken, endToken);
    }
    // ─── Statement Parsers ────────────────────────────────────────────────────
    /**
     * Dispatches to the appropriate statement parsing function based on the
     * current lookahead token.
     */
    parseStatement() {
        while (this.match(token_types_1.TokenType.SEMICOLON)) {
            // ignore empty semicolons
        }
        if (this.stream.isAtEnd())
            return null;
        const current = this.peek();
        switch (current.type) {
            case token_types_1.TokenType.LET:
            case token_types_1.TokenType.VAR:
                return this.parseVariableDeclaration();
            case token_types_1.TokenType.SET:
                return this.parseSetStatement();
            case token_types_1.TokenType.EMIT:
                return this.parseEmitStatement();
            case token_types_1.TokenType.APPLY:
                return this.parseApplyStatement();
            case token_types_1.TokenType.IF:
                return this.parseIfStatement();
            case token_types_1.TokenType.ELSEIF: {
                // Stray ELSEIF without preceding IF
                const strayToken = this.consume();
                this.diagnostics.report({
                    code: 'FPL-S002',
                    message: "Unexpected 'ELSEIF' without a matching 'IF' statement",
                    token: strayToken,
                    expectedToken: 'IF statement before ELSEIF',
                    suggestedFix: "Replace 'ELSEIF' with 'IF' or ensure the preceding 'IF' block was not prematurely closed.",
                });
                const cond = this.parseExpression();
                this.match(token_types_1.TokenType.THEN);
                return this.builder.buildElseIfStatement(cond, [], strayToken, this.stream.previous());
            }
            case token_types_1.TokenType.ELSE: {
                // Stray ELSE outside IF or POLICY
                const strayToken = this.consume();
                this.diagnostics.report({
                    code: 'FPL-S002',
                    message: "Unexpected 'ELSE' without a matching 'IF' or 'WHEN/THEN' block",
                    token: strayToken,
                    expectedToken: 'Statement',
                    suggestedFix: "Remove the stray 'ELSE' or add a matching 'IF ... THEN' block.",
                });
                return this.builder.buildElseStatement([], strayToken, strayToken);
            }
            case token_types_1.TokenType.MATCH:
                return this.parseMatchStatement();
            case token_types_1.TokenType.FOR:
                return this.parseForStatement();
            case token_types_1.TokenType.WHILE:
                return this.parseWhileStatement();
            case token_types_1.TokenType.FOREACH:
                return this.parseForeachStatement();
            case token_types_1.TokenType.TRY:
                return this.parseTryStatement();
            case token_types_1.TokenType.RETURN:
                return this.parseReturnStatement();
            case token_types_1.TokenType.CALL:
                return this.parseCallStatement();
            case token_types_1.TokenType.LOG:
            case token_types_1.TokenType.WARN:
                return this.parseLogStatement();
            case token_types_1.TokenType.ASSERT:
                return this.parseAssertStatement();
            case token_types_1.TokenType.THROW:
                return this.parseThrowStatement();
            case token_types_1.TokenType.BREAK: {
                const tok = this.consume();
                this.match(token_types_1.TokenType.SEMICOLON);
                return this.builder.buildBreakStatement(tok);
            }
            case token_types_1.TokenType.CONTINUE: {
                const tok = this.consume();
                this.match(token_types_1.TokenType.SEMICOLON);
                return this.builder.buildContinueStatement(tok);
            }
            case token_types_1.TokenType.ALLOW:
            case token_types_1.TokenType.DENY:
            case token_types_1.TokenType.REVIEW:
                return this.parseDecisionStatement();
            default:
                return this.parseAssignmentOrExpressionStatement();
        }
    }
    /**
     * Grammar Rule:
     * `set_stmt ::= "SET" lvalue ("=" | "+=" | "-=" | "*=" | "/=") expr`
     */
    parseSetStatement() {
        const startToken = this.consume(); // SET
        const target = this.parsePrimaryOrPostfix();
        const operator = this.consumeAssignmentOperator();
        const value = this.parseExpression();
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildSetStatement(target, operator, value, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `emit_stmt ::= "EMIT" IDENTIFIER "=" expr`
     */
    parseEmitStatement() {
        const startToken = this.consume(); // EMIT
        const targetToken = this.expectIdentifierLike("Expected output variable name after 'EMIT'", 'Specify an OUTPUT variable name, e.g. `EMIT approvedAmount = ...`.');
        this.expect(token_types_1.TokenType.ASSIGN, 'FPL-S002', `Expected '=' after 'EMIT ${targetToken.lexeme}'`, `Add '=' followed by the output expression.`);
        const value = this.parseExpression();
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildEmitStatement(targetToken.lexeme, value, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `apply_stmt ::= "APPLY" IDENTIFIER`
     */
    parseApplyStatement() {
        const startToken = this.consume(); // APPLY
        const ruleToken = this.expectIdentifierLike("Expected rule name after 'APPLY'", 'Provide the name of a declared RULE, e.g. `APPLY CreditScoreCheck`.');
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildApplyStatement(ruleToken.lexeme, startToken, ruleToken);
    }
    /**
     * Grammar Rule:
     * ```ebnf
     * if_stmt ::= "IF" expr "THEN" { statement }
     *             { "ELSEIF" expr "THEN" { statement } }
     *             [ "ELSE" { statement } ]
     *             "END"
     * ```
     */
    parseIfStatement() {
        const startToken = this.consume(); // IF
        this.context.enterBlock('IF');
        const condition = this.parseExpression();
        this.expect(token_types_1.TokenType.THEN, 'FPL-S003', "Missing 'THEN' after IF condition", "Add 'THEN' after the IF condition expression.");
        const thenBranch = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.ELSEIF, token_types_1.TokenType.ELSE, token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
            const stmt = this.parseStatement();
            if (stmt) {
                thenBranch.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        const elseIfBranches = [];
        while (this.stream.check(token_types_1.TokenType.ELSEIF)) {
            const elseIfStart = this.consume(); // ELSEIF
            const elseIfCond = this.parseExpression();
            this.expect(token_types_1.TokenType.THEN, 'FPL-S003', "Missing 'THEN' after ELSEIF condition", "Add 'THEN' after the ELSEIF condition expression.");
            const consequent = [];
            while (!this.stream.isAtEnd() &&
                !this.stream.checkAny(token_types_1.TokenType.ELSEIF, token_types_1.TokenType.ELSE, token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
                const stmt = this.parseStatement();
                if (stmt) {
                    consequent.push(stmt);
                }
                else {
                    this.synchronize();
                }
            }
            elseIfBranches.push(this.builder.buildElseIfStatement(elseIfCond, consequent, elseIfStart, this.stream.previous()));
        }
        let elseBranch = null;
        if (this.stream.check(token_types_1.TokenType.ELSE)) {
            const elseStart = this.consume(); // ELSE
            const elseStmts = [];
            while (!this.stream.isAtEnd() &&
                !this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
                const stmt = this.parseStatement();
                if (stmt) {
                    elseStmts.push(stmt);
                }
                else {
                    this.synchronize();
                }
            }
            elseBranch = this.builder.buildElseStatement(elseStmts, elseStart, this.stream.previous());
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', "Missing 'END' to close IF statement", "Add 'END' to close the IF block.");
        this.context.exitBlock();
        return this.builder.buildIfStatement(condition, thenBranch, elseIfBranches, elseBranch, startToken, endToken);
    }
    /**
     * Grammar Rule:
     * `match_stmt ::= "MATCH" expr { "CASE" expr { "," expr } "THEN" { statement } } [ "DEFAULT" "THEN" { statement } ] "END"`
     */
    parseMatchStatement() {
        const startToken = this.consume(); // MATCH
        this.context.enterBlock('MATCH');
        const discriminant = this.parseExpression();
        const cases = [];
        while (this.stream.check(token_types_1.TokenType.CASE)) {
            const caseStart = this.consume(); // CASE
            const values = [this.parseExpression()];
            while (this.match(token_types_1.TokenType.COMMA)) {
                values.push(this.parseExpression());
            }
            this.expect(token_types_1.TokenType.THEN, 'FPL-S003', "Missing 'THEN' after CASE value", "Add 'THEN' after the CASE value(s).");
            const statements = [];
            while (!this.stream.isAtEnd() &&
                !this.stream.checkAny(token_types_1.TokenType.CASE, token_types_1.TokenType.DEFAULT, token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
                const stmt = this.parseStatement();
                if (stmt) {
                    statements.push(stmt);
                }
                else {
                    this.synchronize();
                }
            }
            cases.push(this.builder.buildCaseClause(values, statements, caseStart, this.stream.previous()));
        }
        let defaultCase = null;
        if (this.stream.check(token_types_1.TokenType.DEFAULT)) {
            const defaultStart = this.consume(); // DEFAULT
            this.match(token_types_1.TokenType.THEN);
            const statements = [];
            while (!this.stream.isAtEnd() &&
                !this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
                const stmt = this.parseStatement();
                if (stmt) {
                    statements.push(stmt);
                }
                else {
                    this.synchronize();
                }
            }
            defaultCase = this.builder.buildDefaultClause(statements, defaultStart, this.stream.previous());
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', "Missing 'END' to close MATCH statement", "Add 'END' to close the MATCH block.");
        this.context.exitBlock();
        return this.builder.buildMatchStatement(discriminant, cases, defaultCase, startToken, endToken);
    }
    /**
     * Grammar Rule:
     * `for_stmt ::= "FOR" IDENTIFIER ("FROM" | "IN" | "=") expr ("TO" | "..") expr [ "STEP" expr ] [ "DO" ] { statement } "END"`
     */
    parseForStatement() {
        const startToken = this.consume(); // FOR
        this.context.enterBlock('LOOP');
        const iterToken = this.expectIdentifierLike("Expected loop variable name after 'FOR'", 'Provide a loop iterator identifier, e.g. `FOR month FROM 1 TO 12 DO`.');
        if (!this.match(token_types_1.TokenType.FROM, token_types_1.TokenType.IN, token_types_1.TokenType.ASSIGN)) {
            this.diagnostics.report({
                code: 'FPL-S002',
                message: `Expected 'FROM' after FOR variable '${iterToken.lexeme}'`,
                token: this.peek(),
                expectedToken: 'FROM',
                suggestedFix: `Use 'FOR ${iterToken.lexeme} FROM <start> TO <end> DO'.`,
            });
        }
        const startExpr = this.parseAdditiveExpression();
        if (!this.match(token_types_1.TokenType.TO, token_types_1.TokenType.RANGE)) {
            this.diagnostics.report({
                code: 'FPL-S002',
                message: "Expected 'TO' or '..' in FOR range",
                token: this.peek(),
                expectedToken: 'TO',
                suggestedFix: "Add 'TO <end>' in the FOR loop header.",
            });
        }
        const endExpr = this.parseAdditiveExpression();
        let stepExpr = null;
        if (this.match(token_types_1.TokenType.STEP)) {
            stepExpr = this.parseAdditiveExpression();
        }
        this.match(token_types_1.TokenType.DO);
        const body = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
            const stmt = this.parseStatement();
            if (stmt) {
                body.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', "Missing 'END' to close FOR loop", "Add 'END' after the FOR loop body.");
        this.context.exitBlock();
        return this.builder.buildForStatement(iterToken.lexeme, startExpr, endExpr, stepExpr, body, startToken, endToken);
    }
    /**
     * Grammar Rule:
     * `while_stmt ::= "WHILE" expr [ "DO" ] { statement } "END"`
     */
    parseWhileStatement() {
        const startToken = this.consume(); // WHILE
        this.context.enterBlock('LOOP');
        const condition = this.parseExpression();
        this.match(token_types_1.TokenType.DO);
        const body = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
            const stmt = this.parseStatement();
            if (stmt) {
                body.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', "Missing 'END' to close WHILE loop", "Add 'END' after the WHILE loop body.");
        this.context.exitBlock();
        return this.builder.buildWhileStatement(condition, body, startToken, endToken);
    }
    /**
     * Grammar Rule:
     * `foreach_stmt ::= "FOREACH" IDENTIFIER "IN" expr [ "DO" ] { statement } "END"`
     */
    parseForeachStatement() {
        const startToken = this.consume(); // FOREACH
        this.context.enterBlock('LOOP');
        const iterToken = this.expectIdentifierLike("Expected item variable name after 'FOREACH'", 'Provide an iterator identifier, e.g. `FOREACH txn IN transactions DO`.');
        this.expect(token_types_1.TokenType.IN, 'FPL-S002', `Expected 'IN' after FOREACH variable '${iterToken.lexeme}'`, `Add 'IN <collection>' after '${iterToken.lexeme}'.`);
        const collection = this.parseExpression();
        this.match(token_types_1.TokenType.DO);
        const body = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
            const stmt = this.parseStatement();
            if (stmt) {
                body.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', "Missing 'END' to close FOREACH loop", "Add 'END' after the FOREACH loop body.");
        this.context.exitBlock();
        return this.builder.buildForeachStatement(iterToken.lexeme, collection, body, startToken, endToken);
    }
    /**
     * Grammar Rule:
     * `try_stmt ::= "TRY" { statement } "CATCH" [ IDENTIFIER ] { statement } "END"`
     */
    parseTryStatement() {
        const startToken = this.consume(); // TRY
        this.context.enterBlock('TRY');
        const tryBlock = [];
        while (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.CATCH, token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
            const stmt = this.parseStatement();
            if (stmt) {
                tryBlock.push(stmt);
            }
            else {
                this.synchronize();
            }
        }
        let catchClause = null;
        if (this.stream.check(token_types_1.TokenType.CATCH)) {
            const catchStart = this.consume(); // CATCH
            let errorVar = null;
            if (this.stream.check(token_types_1.TokenType.IDENTIFIER)) {
                errorVar = this.consume().lexeme;
            }
            const catchBody = [];
            while (!this.stream.isAtEnd() &&
                !this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.POLICY, token_types_1.TokenType.FUNCTION)) {
                const stmt = this.parseStatement();
                if (stmt) {
                    catchBody.push(stmt);
                }
                else {
                    this.synchronize();
                }
            }
            catchClause = this.builder.buildCatchClause(errorVar, catchBody, catchStart, this.stream.previous());
        }
        const endToken = this.expect(token_types_1.TokenType.END, 'FPL-S001', "Missing 'END' to close TRY/CATCH block", "Add 'END' after the CATCH block.");
        this.context.exitBlock();
        return this.builder.buildTryStatement(tryBlock, catchClause, startToken, endToken);
    }
    /**
     * Grammar Rule:
     * `return_stmt ::= "RETURN" [ expr ]`
     */
    parseReturnStatement() {
        const startToken = this.consume(); // RETURN
        let value = null;
        if (!this.stream.isAtEnd() &&
            !this.stream.checkAny(token_types_1.TokenType.END, token_types_1.TokenType.ELSE, token_types_1.TokenType.ELSEIF, token_types_1.TokenType.CASE, token_types_1.TokenType.DEFAULT, token_types_1.TokenType.SEMICOLON) &&
            this.peek().line === startToken.line) {
            value = this.parseExpression();
        }
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildReturnStatement(value, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `call_stmt ::= "CALL" qualified_name [ "(" arg_list ")" | "WITH" named_arg_list ] [ "RETURNS" IDENTIFIER ]`
     */
    parseCallStatement() {
        const startToken = this.consume(); // CALL
        const callee = this.parseQualifiedName();
        const args = [];
        if (this.match(token_types_1.TokenType.LPAREN)) {
            if (!this.stream.check(token_types_1.TokenType.RPAREN) && !this.stream.isAtEnd()) {
                do {
                    if (this.peek().type === token_types_1.TokenType.IDENTIFIER &&
                        this.peek(1).type === token_types_1.TokenType.ASSIGN) {
                        const argName = this.consume().lexeme;
                        this.consume(); // '='
                        const val = this.parseExpression();
                        args.push({ name: argName, value: val });
                    }
                    else {
                        args.push({ name: null, value: this.parseExpression() });
                    }
                } while (this.match(token_types_1.TokenType.COMMA));
            }
            this.expect(token_types_1.TokenType.RPAREN, 'FPL-S002', `Missing ')' in CALL to '${callee}'`, "Add ')' to close the CALL argument list.");
        }
        else if (this.match(token_types_1.TokenType.WITH)) {
            while (!this.stream.isAtEnd() &&
                this.peek().type === token_types_1.TokenType.IDENTIFIER &&
                this.peek(1).type === token_types_1.TokenType.ASSIGN) {
                const argName = this.consume().lexeme;
                this.consume(); // '='
                const val = this.parseExpression();
                args.push({ name: argName, value: val });
                this.match(token_types_1.TokenType.COMMA);
            }
        }
        let returnBinding = null;
        if (this.match(token_types_1.TokenType.RETURNS)) {
            const bindToken = this.expectIdentifierLike("Expected result variable identifier after 'RETURNS'", 'Provide a variable name to store the policy result, e.g. `RETURNS creditResult`.');
            returnBinding = bindToken.lexeme;
        }
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildCallStatement(callee, args, returnBinding, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `log_stmt ::= ("LOG" | "WARN") expr`
     */
    parseLogStatement() {
        const startToken = this.consume(); // LOG or WARN
        const level = startToken.type === token_types_1.TokenType.WARN ? 'WARN' : 'LOG';
        const expr = this.parseExpression();
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildLogStatement(level, expr, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `assert_stmt ::= "ASSERT" expr [ "," expr ]`
     */
    parseAssertStatement() {
        const startToken = this.consume(); // ASSERT
        const condition = this.parseExpression();
        let message = null;
        if (this.match(token_types_1.TokenType.COMMA)) {
            message = this.parseExpression();
        }
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildAssertStatement(condition, message, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `throw_stmt ::= "THROW" [ "ERROR" ] [ "(" ] expr [ "," expr ] [ ")" ]`
     */
    parseThrowStatement() {
        const startToken = this.consume(); // THROW
        this.match(token_types_1.TokenType.ERROR);
        const hasParen = this.match(token_types_1.TokenType.LPAREN);
        const errorCode = this.parseExpression();
        let message = null;
        if (this.match(token_types_1.TokenType.COMMA)) {
            message = this.parseExpression();
        }
        if (hasParen) {
            this.expect(token_types_1.TokenType.RPAREN, 'FPL-S002', "Missing ')' in THROW statement", "Add ')' to close THROW ERROR(...).");
        }
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildThrowStatement(errorCode, message, startToken, this.stream.previous());
    }
    /**
     * Grammar Rule:
     * `decision_stmt ::= ("ALLOW" | "DENY" | "REVIEW") [ "WITH" [ "reason" "=" ] expr [ "AND" "assignTo" "=" expr ] ]`
     */
    parseDecisionStatement() {
        const startToken = this.consume(); // ALLOW | DENY | REVIEW
        const decision = startToken.type;
        let reason = null;
        let assignTo = null;
        if (this.match(token_types_1.TokenType.WITH)) {
            if (this.peek().type === token_types_1.TokenType.IDENTIFIER &&
                this.peek().lexeme === 'reason' &&
                this.peek(1).type === token_types_1.TokenType.ASSIGN) {
                this.consume(); // 'reason'
                this.consume(); // '='
            }
            reason = this.parseComparisonExpression();
            if (this.peek().type === token_types_1.TokenType.AND &&
                this.peek(1).type === token_types_1.TokenType.IDENTIFIER &&
                this.peek(1).lexeme === 'assignTo') {
                this.consume(); // AND
                this.consume(); // assignTo
                this.match(token_types_1.TokenType.ASSIGN);
                assignTo = this.parseComparisonExpression();
            }
        }
        else if (this.match(token_types_1.TokenType.LPAREN)) {
            if (!this.stream.check(token_types_1.TokenType.RPAREN)) {
                reason = this.parseExpression();
            }
            this.expect(token_types_1.TokenType.RPAREN, 'FPL-S002', `Missing ')' after ${decision}(...)`, "Add ')' to close the decision reason.");
        }
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildDecisionStatement(decision, reason, assignTo, startToken, this.stream.previous());
    }
    /**
     * Parses direct assignment (`x = expr`, `x += expr`) or an expression statement.
     */
    parseAssignmentOrExpressionStatement() {
        const startToken = this.peek();
        // If we hit an unparseable token, report error and return null to trigger recovery
        if (startToken.type === token_types_1.TokenType.UNKNOWN) {
            this.consume();
            this.diagnostics.report({
                code: 'FPL-S002',
                message: `Unexpected lexical token '${startToken.lexeme}' in statement`,
                token: startToken,
                expectedToken: 'Valid statement or declaration',
                suggestedFix: `Remove or fix '${startToken.lexeme}'.`,
            });
            return null;
        }
        const expr = this.parseExpression();
        if (this.stream.checkAny(token_types_1.TokenType.ASSIGN, token_types_1.TokenType.PLUS_ASSIGN, token_types_1.TokenType.MINUS_ASSIGN, token_types_1.TokenType.STAR_ASSIGN, token_types_1.TokenType.SLASH_ASSIGN)) {
            const op = this.consumeAssignmentOperator();
            const rhs = this.parseExpression();
            this.match(token_types_1.TokenType.SEMICOLON);
            return this.builder.buildAssignmentStatement(expr, op, rhs, startToken, this.stream.previous());
        }
        this.match(token_types_1.TokenType.SEMICOLON);
        return this.builder.buildExpressionStatement(expr);
    }
    consumeAssignmentOperator() {
        const tok = this.peek();
        switch (tok.type) {
            case token_types_1.TokenType.ASSIGN:
                this.consume();
                return '=';
            case token_types_1.TokenType.PLUS_ASSIGN:
                this.consume();
                return '+=';
            case token_types_1.TokenType.MINUS_ASSIGN:
                this.consume();
                return '-=';
            case token_types_1.TokenType.STAR_ASSIGN:
                this.consume();
                return '*=';
            case token_types_1.TokenType.SLASH_ASSIGN:
                this.consume();
                return '/=';
            default:
                this.expect(token_types_1.TokenType.ASSIGN, 'FPL-S002', `Expected assignment operator ('=', '+=', '-=', '*=', '/=') but found '${tok.lexeme}'`, "Add '=' between the target variable and value expression.");
                return '=';
        }
    }
    // ─── Expression Precedence Hierarchy ──────────────────────────────────────
    /**
     * Entry point for expression parsing (lowest precedence to highest):
     * 1. Null-Coalescing (`??`)
     * 2. Logical OR (`OR`)
     * 3. Logical AND (`AND`)
     * 4. Logical NOT (`NOT`)
     * 5. Comparison (`==`, `=`, `!=`, `<`, `>`, `<=`, `>=`)
     * 6. Membership & Null Checks (`IN`, `NOT IN`, `BETWEEN...AND`, `CONTAINS`, `IS NULL`, `IS NOT NULL`)
     * 7. Range (`..`, `TO`)
     * 8. Additive (`+`, `-`)
     * 9. Multiplicative (`*`, `/`, `%`)
     * 10. Percentage Application (`OF`)
     * 11. Exponentiation (`^`)
     * 12. Unary (`-`, `+`, `NOT`)
     * 13. Postfix & Primary (Literals, Identifiers, Function Calls, Policy Calls, Member `.`, Index `[]`, `(...)`, Ternary `IF...THEN...ELSE`)
     */
    parseExpression() {
        return this.parseNullCoalesceExpression();
    }
    parseNullCoalesceExpression() {
        let left = this.parseLogicalOrExpression();
        while (this.match(token_types_1.TokenType.NULL_COALESCE)) {
            const right = this.parseLogicalOrExpression();
            left = this.builder.buildBinaryExpression('COALESCE', '??', left, right);
        }
        return left;
    }
    parseLogicalOrExpression() {
        let left = this.parseLogicalAndExpression();
        while (this.match(token_types_1.TokenType.OR)) {
            const right = this.parseLogicalAndExpression();
            left = this.builder.buildBinaryExpression('LOGICAL', 'OR', left, right);
        }
        return left;
    }
    parseLogicalAndExpression() {
        let left = this.parseLogicalNotExpression();
        while (this.match(token_types_1.TokenType.AND)) {
            const right = this.parseLogicalNotExpression();
            left = this.builder.buildBinaryExpression('LOGICAL', 'AND', left, right);
        }
        return left;
    }
    parseLogicalNotExpression() {
        if (this.stream.check(token_types_1.TokenType.NOT) && this.peek(1).type !== token_types_1.TokenType.IN) {
            const opToken = this.consume();
            const operand = this.parseLogicalNotExpression();
            return this.builder.buildUnaryExpression('NOT', operand, opToken);
        }
        return this.parseComparisonExpression();
    }
    parseComparisonExpression() {
        let left = this.parseMembershipExpression();
        while (this.stream.checkAny(token_types_1.TokenType.EQUAL_EQUAL, token_types_1.TokenType.NOT_EQUAL, token_types_1.TokenType.GREATER, token_types_1.TokenType.LESS, token_types_1.TokenType.GREATER_EQUAL, token_types_1.TokenType.LESS_EQUAL) ||
            this.isEqualityComparisonAssign()) {
            const opToken = this.consume();
            const right = this.parseMembershipExpression();
            left = this.builder.buildBinaryExpression('COMPARISON', opToken.lexeme, left, right);
        }
        return left;
    }
    /**
     * In FPL (`=`) can be used as an equality comparison inside `WHEN` / `IF` conditions,
     * while `SET x = y` or top-level `x = y` is an assignment statement.
     */
    isEqualityComparisonAssign() {
        if (!this.stream.check(token_types_1.TokenType.ASSIGN))
            return false;
        // Do not consume `=` as comparison if we are at the start of a named argument `arg = val`
        return true;
    }
    parseMembershipExpression() {
        const left = this.parseRangeExpression();
        // `expr IS NULL` or `expr IS NOT NULL`
        if (this.match(token_types_1.TokenType.IS)) {
            const negated = this.match(token_types_1.TokenType.NOT);
            const nullTok = this.expect(token_types_1.TokenType.NULL, 'FPL-S002', "Expected 'NULL' after 'IS'", "Use 'IS NULL' or 'IS NOT NULL'.");
            return this.builder.buildNullCheckExpression(left, negated, nullTok);
        }
        // `expr NOT IN collection`
        if (this.stream.check(token_types_1.TokenType.NOT) && this.peek(1).type === token_types_1.TokenType.IN) {
            this.consume(); // NOT
            this.consume(); // IN
            const collection = this.parseRangeExpression();
            return this.builder.buildInExpression(left, collection, true);
        }
        // `expr IN collection`
        if (this.match(token_types_1.TokenType.IN)) {
            const collection = this.parseRangeExpression();
            return this.builder.buildInExpression(left, collection, false);
        }
        // `expr CONTAINS item`
        if (this.match(token_types_1.TokenType.CONTAINS)) {
            const right = this.parseRangeExpression();
            return this.builder.buildBinaryExpression('COMPARISON', 'CONTAINS', left, right);
        }
        // `expr BETWEEN lower AND upper`
        if (this.match(token_types_1.TokenType.BETWEEN)) {
            const lower = this.parseAdditiveExpression();
            this.expect(token_types_1.TokenType.AND, 'FPL-S002', "Expected 'AND' in BETWEEN...AND range expression", "Use 'value BETWEEN low AND high'.");
            const upper = this.parseAdditiveExpression();
            return this.builder.buildBetweenExpression(left, lower, upper);
        }
        return left;
    }
    parseRangeExpression() {
        let left = this.parseAdditiveExpression();
        if (this.match(token_types_1.TokenType.RANGE)) {
            const right = this.parseAdditiveExpression();
            left = this.builder.buildBinaryExpression('RANGE', '..', left, right);
        }
        return left;
    }
    parseAdditiveExpression() {
        let left = this.parseMultiplicativeExpression();
        while (this.stream.checkAny(token_types_1.TokenType.PLUS, token_types_1.TokenType.MINUS)) {
            const opToken = this.consume();
            const right = this.parseMultiplicativeExpression();
            left = this.builder.buildBinaryExpression('ARITHMETIC', opToken.lexeme, left, right);
        }
        return left;
    }
    parseMultiplicativeExpression() {
        let left = this.parsePercentageOfExpression();
        while (this.stream.checkAny(token_types_1.TokenType.STAR, token_types_1.TokenType.SLASH, token_types_1.TokenType.PERCENT)) {
            const opToken = this.consume();
            const right = this.parsePercentageOfExpression();
            left = this.builder.buildBinaryExpression('ARITHMETIC', opToken.lexeme, left, right);
        }
        return left;
    }
    parsePercentageOfExpression() {
        let left = this.parsePowerExpression();
        while (this.match(token_types_1.TokenType.OF)) {
            const right = this.parsePowerExpression();
            left = this.builder.buildBinaryExpression('PERCENTAGE_OF', 'OF', left, right);
        }
        return left;
    }
    parsePowerExpression() {
        const left = this.parseUnaryExpression();
        if (this.match(token_types_1.TokenType.CARET)) {
            const right = this.parseUnaryExpression();
            return this.builder.buildBinaryExpression('ARITHMETIC', '^', left, right);
        }
        return left;
    }
    parseUnaryExpression() {
        if (this.stream.checkAny(token_types_1.TokenType.MINUS, token_types_1.TokenType.PLUS, token_types_1.TokenType.NOT)) {
            const opToken = this.consume();
            const operand = this.parseUnaryExpression();
            return this.builder.buildUnaryExpression(opToken.lexeme, operand, opToken);
        }
        return this.parsePrimaryOrPostfix();
    }
    parsePrimaryOrPostfix() {
        let expr = this.parsePrimaryExpression();
        while (!this.stream.isAtEnd()) {
            if (this.match(token_types_1.TokenType.DOT)) {
                const propToken = this.expectIdentifierLike("Expected property or method name after '.'", 'Provide a valid field name, e.g. `applicant.creditScore`.');
                // Method call on member: `obj.method(a, b)`
                if (this.match(token_types_1.TokenType.LPAREN)) {
                    const args = this.parseArgumentExpressionList();
                    const closeParen = this.expect(token_types_1.TokenType.RPAREN, 'FPL-S002', `Missing ')' in method call '.${propToken.lexeme}(...)'`, "Add ')' to close the argument list.");
                    const memberNode = this.builder.buildMemberExpression(expr, propToken);
                    expr = this.builder.buildFunctionCallExpression(`${this.printer.getNodeLabel(memberNode)}`, args, propToken, closeParen);
                }
                else {
                    expr = this.builder.buildMemberExpression(expr, propToken);
                }
                continue;
            }
            if (this.match(token_types_1.TokenType.LBRACKET)) {
                const indexExpr = this.parseExpression();
                const closeBracket = this.expect(token_types_1.TokenType.RBRACKET, 'FPL-S002', "Missing closing ']' in index expression", "Add ']' after the array index expression.");
                expr = this.builder.buildIndexExpression(expr, indexExpr, closeBracket);
                continue;
            }
            break;
        }
        return expr;
    }
    parsePrimaryExpression() {
        const token = this.peek();
        // 1. Literals
        switch (token.type) {
            case token_types_1.TokenType.INTEGER:
                return this.builder.buildLiteralExpression('INTEGER', this.consume());
            case token_types_1.TokenType.DECIMAL:
                return this.builder.buildLiteralExpression('DECIMAL', this.consume());
            case token_types_1.TokenType.CURRENCY:
                return this.builder.buildLiteralExpression('CURRENCY', this.consume());
            case token_types_1.TokenType.PERCENTAGE:
                return this.builder.buildLiteralExpression('PERCENTAGE', this.consume());
            case token_types_1.TokenType.BOOLEAN:
                return this.builder.buildLiteralExpression('BOOLEAN', this.consume());
            case token_types_1.TokenType.STRING:
                return this.builder.buildLiteralExpression('STRING', this.consume());
            case token_types_1.TokenType.DATE:
                return this.builder.buildLiteralExpression('DATE', this.consume());
            case token_types_1.TokenType.NULL:
                return this.builder.buildLiteralExpression('NULL', this.consume());
        }
        // 2. Inline Ternary Expression: `IF cond THEN expr1 ELSE expr2`
        if (this.match(token_types_1.TokenType.IF)) {
            const condition = this.parseExpression();
            this.expect(token_types_1.TokenType.THEN, 'FPL-S003', "Missing 'THEN' in inline IF...THEN...ELSE expression", "Add 'THEN' after the inline IF condition.");
            const consequent = this.parseExpression();
            this.expect(token_types_1.TokenType.ELSE, 'FPL-S002', "Missing 'ELSE' in inline IF...THEN...ELSE expression", "Inline conditional expressions require an 'ELSE' branch.");
            const alternate = this.parseExpression();
            return this.builder.buildTernaryExpression(condition, consequent, alternate, token);
        }
        // 3. Policy Call Expression: `CALL PolicyName WITH ...` or `CALL PolicyName(...)`
        if (this.match(token_types_1.TokenType.CALL)) {
            const policyName = this.parseQualifiedName();
            const args = [];
            if (this.match(token_types_1.TokenType.LPAREN)) {
                if (!this.stream.check(token_types_1.TokenType.RPAREN) && !this.stream.isAtEnd()) {
                    do {
                        args.push({ name: null, value: this.parseExpression() });
                    } while (this.match(token_types_1.TokenType.COMMA));
                }
                this.expect(token_types_1.TokenType.RPAREN, 'FPL-S002', `Missing ')' in policy call '${policyName}'`, "Add ')' to close the policy call arguments.");
            }
            else if (this.match(token_types_1.TokenType.WITH)) {
                while (!this.stream.isAtEnd() &&
                    this.peek().type === token_types_1.TokenType.IDENTIFIER &&
                    this.peek(1).type === token_types_1.TokenType.ASSIGN) {
                    const argName = this.consume().lexeme;
                    this.consume(); // '='
                    const val = this.parseExpression();
                    args.push({ name: argName, value: val });
                    this.match(token_types_1.TokenType.COMMA);
                }
            }
            let returnBinding = null;
            if (this.match(token_types_1.TokenType.RETURNS)) {
                returnBinding = this.expectIdentifierLike("Expected identifier after 'RETURNS'", 'Specify a return variable binding.').lexeme;
            }
            return this.builder.buildPolicyCallExpression(policyName, args, returnBinding, token, this.stream.previous());
        }
        // 4. Parenthesized Expression: `( expr )`
        if (this.match(token_types_1.TokenType.LPAREN)) {
            const inner = this.parseExpression();
            const closeParen = this.expect(token_types_1.TokenType.RPAREN, 'FPL-S002', "Missing closing ')' in parenthesized expression", "Add ')' to balance the opening '('.");
            return this.builder.buildParenthesizedExpression(inner, token, closeParen);
        }
        // 5. Array Literal: `[ expr, ... ]`
        if (this.match(token_types_1.TokenType.LBRACKET)) {
            const elements = [];
            if (!this.stream.check(token_types_1.TokenType.RBRACKET) && !this.stream.isAtEnd()) {
                do {
                    if (this.stream.check(token_types_1.TokenType.RBRACKET))
                        break;
                    elements.push(this.parseExpression());
                } while (this.match(token_types_1.TokenType.COMMA));
            }
            const closeBracket = this.expect(token_types_1.TokenType.RBRACKET, 'FPL-S002', "Missing closing ']' in array literal", "Add ']' to close the array literal.");
            return this.builder.buildArrayLiteral(elements, token, closeBracket);
        }
        // 6. Object Literal: `{ key: expr, ... }`
        if (this.match(token_types_1.TokenType.LBRACE)) {
            const properties = [];
            if (!this.stream.check(token_types_1.TokenType.RBRACE) && !this.stream.isAtEnd()) {
                do {
                    if (this.stream.check(token_types_1.TokenType.RBRACE))
                        break;
                    const propKey = this.expectIdentifierLike('Expected object property key', 'Provide an identifier key followed by `:`.');
                    this.expect(token_types_1.TokenType.COLON, 'FPL-S002', `Expected ':' after object property key '${propKey.lexeme}'`, `Use '${propKey.lexeme}: <value>'.`);
                    const propVal = this.parseExpression();
                    properties.push(this.builder.buildObjectProperty(propKey.lexeme, propVal, propKey));
                } while (this.match(token_types_1.TokenType.COMMA));
            }
            const closeBrace = this.expect(token_types_1.TokenType.RBRACE, 'FPL-S002', "Missing closing '}' in object literal", "Add '}' to close the object literal.");
            return this.builder.buildObjectLiteral(properties, token, closeBrace);
        }
        // 7. Identifier or Function Call: `ident` or `ident(arg1, arg2)` or `Namespace.func(arg1)`
        if (token.type === token_types_1.TokenType.IDENTIFIER ||
            BUILTIN_TYPE_TOKEN_SET.has(token.type)) {
            const identToken = this.consume();
            // Direct function call: `func(a, b)`
            if (this.match(token_types_1.TokenType.LPAREN)) {
                const args = this.parseArgumentExpressionList();
                const closeParen = this.expect(token_types_1.TokenType.RPAREN, 'FPL-S002', `Missing closing ')' in call to '${identToken.lexeme}(...)'`, `Add ')' to close the argument list for '${identToken.lexeme}'.`);
                return this.builder.buildFunctionCallExpression(identToken.lexeme, args, identToken, closeParen);
            }
            return this.builder.buildIdentifierExpression(identToken);
        }
        // 8. Unexpected Token / EOF in Expression -> Report Error and Synthesize Placeholder
        const offending = this.stream.isAtEnd() ? this.peek() : this.consume();
        this.diagnostics.report({
            code: offending.type === token_types_1.TokenType.EOF ? 'FPL-S013' : 'FPL-S002',
            message: offending.type === token_types_1.TokenType.EOF
                ? 'Unexpected end of file (EOF) while parsing expression'
                : `Unexpected token '${offending.lexeme}' (${offending.type}) in expression`,
            token: offending,
            expectedToken: 'Expression (identifier, literal, function call, or parenthesized expression)',
            suggestedFix: offending.type === token_types_1.TokenType.EOF
                ? 'Complete the incomplete expression before the end of the file.'
                : `Replace '${offending.lexeme}' with a valid expression.`,
        });
        return this.builder.buildIdentifierExpression({
            ...offending,
            type: token_types_1.TokenType.IDENTIFIER,
            lexeme: '<error>',
        });
    }
    parseArgumentExpressionList() {
        const args = [];
        if (!this.stream.check(token_types_1.TokenType.RPAREN) && !this.stream.isAtEnd()) {
            do {
                if (this.stream.check(token_types_1.TokenType.RPAREN))
                    break;
                args.push(this.parseExpression());
            } while (this.match(token_types_1.TokenType.COMMA));
        }
        return args;
    }
    // ─── Helper Predicates ────────────────────────────────────────────────────
    parseQualifiedName() {
        const first = this.expectIdentifierLike('Expected policy or function identifier', 'Provide a valid identifier.');
        let name = first.lexeme;
        while (this.match(token_types_1.TokenType.DOT)) {
            const nextPart = this.expectIdentifierLike("Expected identifier after '.' in qualified name", 'Provide the member policy or function name.');
            name += `.${nextPart.lexeme}`;
        }
        return name;
    }
    expectIdentifierLike(message, suggestedFix) {
        const tok = this.peek();
        if (tok.type === token_types_1.TokenType.IDENTIFIER ||
            BUILTIN_TYPE_TOKEN_SET.has(tok.type)) {
            return this.consume();
        }
        return this.expect(token_types_1.TokenType.IDENTIFIER, 'FPL-S002', message, suggestedFix);
    }
    isTopLevelDeclarationStart() {
        return this.stream.checkAny(token_types_1.TokenType.IMPORT, token_types_1.TokenType.CONST, token_types_1.TokenType.FUNCTION, token_types_1.TokenType.POLICY, token_types_1.TokenType.RULE);
    }
    isTopLevelStarterExceptRule() {
        return this.stream.checkAny(token_types_1.TokenType.IMPORT, token_types_1.TokenType.CONST, token_types_1.TokenType.FUNCTION, token_types_1.TokenType.POLICY);
    }
}
exports.Parser = Parser;
/**
 * Convenience API that parses a `Token[]` stream directly into a {@link ParseResult}.
 */
function parseTokens(tokens) {
    const parser = new Parser(tokens);
    return parser.parse();
}
//# sourceMappingURL=parser.js.map